compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableScripts: false

enableTransparentWorkspaces: false

nodeLinker: node-modules

packageExtensions:
  react-simple-pull-to-refresh@*:
    peerDependencies:
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
