"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Timestamp = exports.deserializeClock = exports.serializeClock = exports.makeClientId = exports.makeClock = exports.setClock = exports.getClock = exports.merkle = void 0;
var merkle = require("./merkle");
exports.merkle = merkle;
var timestamp_1 = require("./timestamp");
Object.defineProperty(exports, "getClock", { enumerable: true, get: function () { return timestamp_1.getClock; } });
Object.defineProperty(exports, "setClock", { enumerable: true, get: function () { return timestamp_1.setClock; } });
Object.defineProperty(exports, "makeClock", { enumerable: true, get: function () { return timestamp_1.makeClock; } });
Object.defineProperty(exports, "makeClientId", { enumerable: true, get: function () { return timestamp_1.makeClientId; } });
Object.defineProperty(exports, "serializeClock", { enumerable: true, get: function () { return timestamp_1.serializeClock; } });
Object.defineProperty(exports, "deserializeClock", { enumerable: true, get: function () { return timestamp_1.deserializeClock; } });
Object.defineProperty(exports, "Timestamp", { enumerable: true, get: function () { return timestamp_1.Timestamp; } });
